name: Build, Lint, and Deploy to Firebase

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22' 

    - name: Install dependencies
      run: npm ci

    - name: Run Super Linter
      uses: github/super-linter@v5
      env:
        VALIDATE_ALL_CODEBASE: true
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

    - name: Build project
      run: npm run build 

    - name: Deploy to Firebase Hosting
      uses: w9jds/firebase-action@v2.2.0
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
